testing_mode = true
payment_provider = "stripe" #bmac if using Buy Me A Coffee
stripe_api_key_test = "rk_test_51Nes7qLknGnnEOjyx1k9gmDXDvQzH85GOu9gz9HPvwMkXjTwmwyIF7EVlUSXz0VO2WGp8XvGTKQbLDMm98eQm30800dO6NibyQ" #only needed if using Stripe
stripe_api_key = "sk_live_..." #only needed if using Stripe
stripe_link = "https://buy.stripe.com/..." #only needed if using Stripe
stripe_link_test = "https://buy.stripe.com/test_9AQ5kSbtu0ew3ZefYY" #only needed if using Stripe
client_id = "62418760001-5lfbh5ugeva5a3e78d985g58lm77hmn1.apps.googleusercontent.com"
client_secret = "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"
redirect_url_test = 'http://localhost:8501/'
redirect_url = "https://saas-basic-app.streamlit.app"
bmac_api_key = "ey..." #only needed if using buy me a coffee
bmac_link = "https://www.buymeacoffee.com/..." #only needed if using buy me a coffee